#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of C++Py-Tree.
# 
# C++Py-Tree is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# C++Py-Tree is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with C++Py-Tree.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T options
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L options.old <(echo \
'$ cd ../src/tree
$ export LD_LIBRARY_PATH=.:abc:cxxpy
$ ./tree --dump-opt
home-dir:       .
action:         pretty-print
ext-func-name:  printer::pretty_print
input-type:     text
debug:          no
debug-ext-func: no
help-ext-func:  no
verbose:        no
argc:           0
ext-argc:       0
$ ./tree -F printer.so -- --dump-opt
home-dir:       .
action:         print-ast
ext-func-name:  -
indent-dots:    no
debug:          no
debug-ext-func: no
help-ext-func:  no
verbose:        no
argc:           0
ext-argc:       0
$ ./tree -F cxxpy/cxxpy.so -- --dump-opt
home-dir:       cxxpy
action:         type-check
ext-func-name:  -
casts-type:     strict-casts
trace-eval:     no
debug:          no
debug-ext-func: no
help-ext-func:  no
verbose:        no
argc:           0
ext-argc:       0
$ ./tree -F abc/abc.so -- --dump-opt
home-dir:       abc
action:         type-check
ext-func-name:  -
casts-type:     strict-casts
trace-eval:     no
debug:          no
debug-ext-func: no
help-ext-func:  no
verbose:        no
argc:           0
ext-argc:       0'
) -L options.new <(
echo '$ cd ../src/tree'
cd ../src/tree 2>&1 ||
echo 'command failed: cd ../src/tree'

echo '$ export LD_LIBRARY_PATH=.:abc:cxxpy'
export LD_LIBRARY_PATH=.:abc:cxxpy 2>&1 ||
echo 'command failed: export LD_LIBRARY_PATH=.:abc:cxxpy'

echo '$ ./tree --dump-opt'
./tree --dump-opt 2>&1 ||
echo 'command failed: ./tree --dump-opt'

echo '$ ./tree -F printer.so -- --dump-opt'
./tree -F printer.so -- --dump-opt 2>&1 ||
echo 'command failed: ./tree -F printer.so -- --dump-opt'

echo '$ ./tree -F cxxpy/cxxpy.so -- --dump-opt'
./tree -F cxxpy/cxxpy.so -- --dump-opt 2>&1 ||
echo 'command failed: ./tree -F cxxpy/cxxpy.so -- --dump-opt'

echo '$ ./tree -F abc/abc.so -- --dump-opt'
./tree -F abc/abc.so -- --dump-opt 2>&1 ||
echo 'command failed: ./tree -F abc/abc.so -- --dump-opt'
)

